### ISSUE TITLE
Add to FAQ: When do I need to construct an *.amd.json file

### ISSUE THREAD

**Issue by hhzl** [amber-smalltalk/amber-documentation#45]
This question is addressed on the wiki. Add link here.

**Comment by mkroehnert** [comment]
Instead of linking, I think the article should be copied to this
documentation and removed from the wiki.
Otherwise we have the information spread over several places.

**Comment by hhzl** [comment]
@mkroehnert which article? Link?

**Comment by sebastianconcept** [comment]
I agree with @mkroehnert on deprecating GitHub wiki once we move them there and promoting our own docs in site. Our SEO will be better and we can embeed, architect and style in ways the wiki will never allow

**Comment by hhzl** [comment]
@sebastianconcept my question here is not _if_ wiki pages should be _deprecated_ when the documentation is in place but which piece of info is useful for the question raised in this issue #45.

**The answer** is here to a certain extent on the page about the [Amber-config](https://github.com/amber-smalltalk/amber/wiki/Amber-Config) command.

**Comment by mkroehnert** [comment]
@hhzl since you wrote the statement
`This question is addressed on the wiki.`
I assumed that an article was already present.

**Comment by hhzl** [comment]
@mkroehnert And if you actually read the [Amber config](https://github.com/amber-smalltalk/amber/wiki/Amber-Config) page you probably agree with me that your assumption was correct. I.E. the information is there but has to be put into another form for an FAQ question.

**Comment by mkroehnert** [comment]
@hhzl sorry, you are confusing me.
First, you ask me about which article I am talking about and then tell me what I should have read and thus repeating what you already wrote right before my answer??
Next time it would probably better to add the link immediately to avoid such situations.

**Comment by sebastianconcept** [comment]
+1  @mkroehnert 

When you don't work exposing links that facilitate access to continue the contributing process, people feels that you want to actually make it harder on purpose.

The better players we are with each other, the more results the project will get

**Comment by hhzl** [comment]
Superseeded by https://github.com/amber-smalltalk/amber-documentation/issues/55
