### ISSUE TITLE
Add to FAQ: Why should I not refer to .min files in *.amd.json files?

### ISSUE THREAD

**Issue by hhzl** [amber-smalltalk/amber-documentation#47]

**Comment by ghost** [comment]
`.min.js` files are already minified, thus not readable / debuggable. But you develop an app (or lib), and during development (set by `grunt devel`) it is much better to have all files in non-minified human-readable form. Once you want to deploy an app, you do `grunt deploy` which minifies every file your app uses, including libraries. So, in deployed form, you don't lose the minifier advantage.

**Comment by hhzl** [comment]
+1

**Comment by sebastianconcept** [comment]
_I would be okay with this reviewed version:_

`.min.js` files are minified, thus not really readable and debuggable. During your app (or lib) development it is much better to have all source code available as non-minified human-readable form hence use in the *.amd.json file their non-minified version configured by `grunt devel`. Once you want to deploy your app, you do `grunt deploy` and it will minify every file your app is set to use, including libraries. 

If you don't want or need, of think is more efficient to use the libraries' own minified versions you can do it with the expected drawback of being non-debbugable.

**Comment by hhzl** [comment]
Copied to [wiki](https://github.com/amber-smalltalk/amber/wiki/FAQ#why-should-i-not-refer-to-min-files-in-amdjson-files).
