### ISSUE TITLE
Add to FAQ: What version is the amber website running?

### ISSUE THREAD

**Issue by hhzl** [amber-smalltalk/amber-documentation#51]
From ML:

**Answer**
1. Open IDE
2. Navigate to packages `Kernel-Infrastructure`
   
   SmalltalkImage version

![amber version on web site 2015-01-21 04 25 18](https://cloud.githubusercontent.com/assets/1112023/5831301/aa6948a4-a127-11e4-8a4c-d38478d0b14c.png)

**Comment by hhzl** [comment]
Added to wiki https://github.com/amber-smalltalk/amber/wiki/FAQ#what-version-is-the-amber-website-running

**Comment by mkroehnert** [comment]
Actually, you just need to evaluate and print `Smalltalk version` in an IDE
workspace.

**Comment by hhzl** [comment]
Thanks, `Smalltalk version` added to https://github.com/amber-smalltalk/amber-documentation/blob/gh-pages/faq.md
