### ISSUE TITLE
What does the caret ^ do in front of version numbers?

### ISSUE THREAD

**Issue by hhzl** [amber-smalltalk/amber-documentation#54]
A caret in front of a version number in `bower.json` as for example  `^0.14`  means that if you run `bower install` the latest compatible version will be pulled in. `bower.json` still shows the earlier version number but the file `bower.json` which is contained in `bower_components/amber` shows the more recent version number.

**Comment by ghost** [comment]
A caret in front of a version number in `bower.json` as for example  `^0.14.1`  means that if you run `bower install` the latest compatible version will be pulled in. The `bower.json` is still the same after install, by design, as things like "^0.14.1" just _describe_ what versions of the dependency are required. But actually installed `bower_components/amber` contains the more recent version number as can be examined in `bower_components/amber/,bower.json` showing the resolved version (or just by running the IDE and printing `Smalltalk version` in Workspace).

**Comment by hhzl** [comment]
https://github.com/amber-smalltalk/amber-documentation/blob/gh-pages/faq.md

I will close the issue in 7 days unless somebody thinks the answer should be changed.

**Comment by sebastianconcept** [comment]
Good one @hhzl,  is indeed a frequent question but I think it needs a bit more space to elaborate. For example, I aggressively use automation and need things to rebuild properly all the time so the short steps would not provide enough background.
I've started a How-to so we can explain the steps, why they are there and reference for more details.
Doesn't have to be long either, just 3 or 4 paragraphs (and we'll stick to the inverted pyramid principle)

![](http://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Inverted_pyramid_2.svg/400px-Inverted_pyramid_2.svg.png)

**Comment by hhzl** [comment]
Fine, let's have a short answer (easy to memorize) and a link to a how-to which elaborates it.  Please go ahead with the how-to.  I will not close the issue before March 1st.

**Comment by ghost** [comment]
Hannes Hirzel wrote:

> Fine, let's have a short answer (easy to memorize) and a link to a
> how-to which elaborates it. Please go ahead with the how-to.

Short answer is:

"^0.14.1" is just a shortcut for ">=0.14.1 <0.15.0". Contrary to common 
misconception, package.json / bower.json do not show version that is 
installed, but on the contrary they describe what interval of versions 
is required for install.

**Comment by hhzl** [comment]
Excellent

I have updated https://github.com/amber-smalltalk/amber-documentation/blob/gh-pages/faq.md
with this concise answer.

## Text to be elaborated into a HowTo?

Maybe? @sebastianconcept 

A caret in front of a version number in `bower.json` as for example  `^0.14.1`  means that if you run `bower install` the latest compatible version will be pulled in. The `bower.json` is still the same after install, by design, as things like "^0.14.1" just _describe_ what versions of the dependency are required. But actually installed `bower_components/amber` contains the more recent version number as can be examined in `bower_components/amber/,bower.json` showing the resolved version (or just by running the IDE and printing `Smalltalk version` in Workspace).

**Comment by sebastianconcept** [comment]
looking good!

**Comment by hhzl** [comment]
Added ref to https://github.com/npm/node-semver#caret-ranges-123-025-004
